---
- name: Setup locale
  locale_gen: name=ru_RU.UTF-8 state=present

- name: Add ruby repo
  apt_repository: repo='ppa:brightbox/ruby-ng' state=present

- name: Install stuff
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - git
    - ruby2.1
    - ruby2.1-dev
    - ruby-switch
    - bundler
    - unoconv

- name: Set default ruby
  shell: ruby-switch --set ruby2.1

- name: Checkout repo
  sudo: no
  git: repo=https://github.com/mix86/unoconv3.git
       dest=/home/ubuntu/unoconv3
       accept_hostkey=yes
       force=yes

- name: Bundle
  sudo: no
  shell: bundle install --path vendor/bundle --quiet
         chdir=/home/ubuntu/unoconv3
